[package]
name = "charcoal-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
solang-parser = "0.3.4"
toml = "0.8.22"
serde_yaml = "0.9.33"
num-bigint = "0.4.6"
num-traits = "0.2.19"
convert_case = "0.8.0"
